DROP DATABASE FORUM;

CREATE DATABASE FORUM default character set utf8 collate utf8_general_ci;

USE FORUM;

CREATE TABLE user(
	id INT NOT NULL AUTO_INCREMENT,
	account CHAR(40) NOT NULL unique,
	password CHAR(40) NOT NULL,
	md5_key CHAR(40) NOT NULL,
	crete_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY ( id )
)ENGINE=InnoDB AUTO_INCREMENT=1018 DEFAULT CHARSET=utf8;

CREATE TABLE artcle(
	id INT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	author CHAR(40) NOT NULL,
	title CHAR(40) NOT NULL,
	content CHAR(40) NOT NULL,
	created_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

alter TABLE artcle add constraint FK_ID foreign key(user_id) REFERENCES user(id);
